name: gas_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  webview_flutter_wkwebview: "3.5.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  flutter_svg: ^2.0.7
  jwt_decode: ^0.3.1
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  image_network: ^2.5.4+1
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  email_validator: ^2.1.17
  barcode_scan2: ^4.2.4
  quickalert: ^1.0.1
  expandable: ^5.0.1
  basic_utils: ^5.6.1
  flutter_map: ^5.0.0
  flutter_map_location_marker: ^7.0.2
  flutter_compass: ^0.7.0
  flutter_map_marker_popup: ^5.2.0
  latlong2: ^0.9.0
  getwidget: ^3.1.1
  indexed: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/marker/
    - assets/login/
    - assets/base/
